package cn.getdone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORY_TASK.
 */
public class HistoryTask {

    private Long id;
    /** Not-null value. */
    private String title;
    private int priority;
    /** Not-null value. */
    private java.util.Date createTime;
    private java.util.Date excuteTime;
    private Long friendId;

    public HistoryTask() {
    }

    public HistoryTask(Long id) {
        this.id = id;
    }

    public HistoryTask(Long id, String title, int priority, java.util.Date createTime, java.util.Date excuteTime, Long friendId) {
        this.id = id;
        this.title = title;
        this.priority = priority;
        this.createTime = createTime;
        this.excuteTime = excuteTime;
        this.friendId = friendId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    /** Not-null value. */
    public java.util.Date getCreateTime() {
        return createTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getExcuteTime() {
        return excuteTime;
    }

    public void setExcuteTime(java.util.Date excuteTime) {
        this.excuteTime = excuteTime;
    }

    public Long getFriendId() {
        return friendId;
    }

    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

}
