package cn.getdone.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.getdone.dao.Task;
import cn.getdone.dao.HistoryTask;

import cn.getdone.dao.TaskDao;
import cn.getdone.dao.HistoryTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig historyTaskDaoConfig;

    private final TaskDao taskDao;
    private final HistoryTaskDao historyTaskDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        historyTaskDaoConfig = daoConfigMap.get(HistoryTaskDao.class).clone();
        historyTaskDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        historyTaskDao = new HistoryTaskDao(historyTaskDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(HistoryTask.class, historyTaskDao);
    }
    
    public void clear() {
        taskDaoConfig.getIdentityScope().clear();
        historyTaskDaoConfig.getIdentityScope().clear();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public HistoryTaskDao getHistoryTaskDao() {
        return historyTaskDao;
    }

}
