package me.jeremyhe.getdone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHARE_TASK.
 */
public class ShareTask {

    private Long id;
    /** Not-null value. */
    private String title;
    private int priority;
    private int status;
    private java.util.Date excuteTime;
    private Long friendId;

    public ShareTask() {
    }

    public ShareTask(Long id) {
        this.id = id;
    }

    public ShareTask(Long id, String title, int priority, int status, java.util.Date excuteTime, Long friendId) {
        this.id = id;
        this.title = title;
        this.priority = priority;
        this.status = status;
        this.excuteTime = excuteTime;
        this.friendId = friendId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public java.util.Date getExcuteTime() {
        return excuteTime;
    }

    public void setExcuteTime(java.util.Date excuteTime) {
        this.excuteTime = excuteTime;
    }

    public Long getFriendId() {
        return friendId;
    }

    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

}
